Wordle Solver
=============

The idea is to take at each step the guess that would result in the lowest expected number of words that are still possible.

We do some precomputation with respect to that, by computing a matrix that returns an encoding of the result (position of all yellow and green letters) where in the row we have the correct word and in the column the guess.

In [1]:
import itertools

import numpy as np

In [2]:
# parse the word list
def file_to_list(f):
    return list({line.strip() for line in f})
with open('wordle_words.txt') as f:
    words = file_to_list(f)
len(words)

2315

In [3]:
# convert to a numpy array
def list_to_array(l):
    return np.array([[ord(c) for c in word] for word in l])
words_a = list_to_array(words)

In [4]:
# n x n x 5 array representing which letters are green when the guess (dim 9) is done against the true word (dim 1)

%time green = words_a[:, np.newaxis, :] == words_a[np.newaxis, :, :]  # numpy vectorization magic
green.shape

CPU times: user 81.3 ms, sys: 6.32 ms, total: 87.6 ms
Wall time: 85.7 ms


(2315, 2315, 5)

In [5]:
# quick check

print(words[0], words[2])
green[0, 2]

condo tangy


array([False, False,  True, False, False])

In [6]:
# same, but for yellow. This requires some numpy black magic. But it's concise and fast.

%time yellow = (words_a[:, np.newaxis, :, np.newaxis] == words_a[np.newaxis, :, np.newaxis, :]).sum(axis=3).astype(bool)
yellow.shape

CPU times: user 804 ms, sys: 87.1 ms, total: 891 ms
Wall time: 891 ms


(2315, 2315, 5)

In [7]:
print(words[4], words[6])
yellow[4,6]

faint brown


array([False, False, False,  True, False])

In [8]:
def encode(a, base):
    """Encode the last dimension of an array as a single integer that is a function of its values.

    The way we do it is by encoding a 1d array x as sum(v * base**i for i, v in enumerate(x)).
    """

    powers = (base ** np.arange(a.shape[-1])).reshape(((1,) * (len(a.shape) - 1)) + (-1,))
    return (a * powers).sum(axis=-1)
encode(np.array([1, 4, 2]), 5)  # 1 + 4 * 5 + 2 * 25 = 71

71

In [9]:
# This is the encoded guess-result matrix. Consider each position as 3 (green), 1 (yellow) or 0 (grey)
# encoded[i, j] will be sum(v[k] * 4 ** k for k in range(5)) where v[k] is the value above for green/yellow/grey and k is the position

%time encoded = encode(green, 4) * 2 + encode(yellow, 4)
encoded.shape

CPU times: user 369 ms, sys: 104 ms, total: 473 ms
Wall time: 471 ms


(2315, 2315)

In [10]:
# here's what our matrix looks like. The visualization says we have 501 columns but it's a bug.

encoded

array([[1023,   64,   48, ...,   16,    0,    0],
       [ 256, 1023,   20, ...,   64,    0,   16],
       [  48,    5, 1023, ...,   16,  192,   12],
       ...,
       [  64,   16,   64, ..., 1023,  772,  260],
       [   0,    0,  192, ...,  788, 1023,  276],
       [   0,    4,   12, ...,  320,  320, 1023]])

In [11]:
def choose(encoded, active):
    """Choose a guess given that the columns in active are possible.

    Returns the index of the word to choose and the expected number of possible words after the guess.

    Could be improved by considering the possibility of choosing a word that's not possible.
    """

    best, best_score = 0, np.inf
    for i in active:
        row = encoded[i, active]
        bincount = np.bincount(row)  # number of possibilities for each result
        score = (bincount * (bincount - 1)).sum() / bincount.sum()  # expected number of still-valid alternatives
        if score < best_score:
            best, best_score = i, score
    return best, best_score

In [12]:
# The word with the best score as a first attempt

best, best_score = choose(encoded, np.arange(words_a.shape[0]))
print(words[best], best_score)

raise 60.00086393088553


In [13]:
def play(word=None, verbose=True):
    """Play the game. If verbose, print stuff to see what's happening.

    Returns the number of guesses needed to get the right word.
    """

    if word is None:
        word = np.random.randint(len(words))
    # print(f"The word is {words[word].upper()}")
    active = np.arange(len(words))
    for i in itertools.count():
        guess, guess_score = choose(encoded, active)
        if verbose:
            print(f"Guess: {words[guess].upper()} (score {guess_score:.2f})")
            response = ['G' if g else 'Y' if y else '-'
                    for g, y in zip(green[guess, word], yellow[guess, word])]
            print(''.join(response))
        if guess == word:
            if verbose:
                print("Correct!")
            break
        active = active[encoded[guess, active] == encoded[guess, word]]  # update the possible words
        if verbose:
            candidates = ' '.join(words[candidate].upper() for candidate in active[:5])
            if active.size > 5:
                candidates = candidates + " ..."
            print(f"Remaining possible words: {active.size} ({candidates})")
        assert word in active
    return i + 1

In [14]:
# example play
play()

Guess: RAISE (score 60.00)
YY---
Remaining possible words: 78 (MORAL ARBOR ORGAN BORAX CORAL ...)
Guess: ACORN (score 4.74)
Y--Y-
Remaining possible words: 12 (GRAPH DRAMA DRAWL TRAMP FRAUD ...)
Guess: WRATH (score 1.17)
YGG--
Remaining possible words: 2 (DRAWL BRAWL)
Guess: DRAWL (score 0.00)
-GGGG
Remaining possible words: 1 (BRAWL)
Guess: BRAWL (score 0.00)
GGGGG
Correct!


5

In [15]:
# another one, 'cause we're getting curious and having some fun
play()

Guess: RAISE (score 60.00)
-Y--G
Remaining possible words: 41 (AGATE BLAME PLATE HEAVE FLAME ...)
Guess: PLATE (score 3.76)
-GG-G
Remaining possible words: 7 (BLAME FLAME GLAZE FLAKE BLAZE ...)
Guess: BLAME (score 1.14)
GGGGG
Correct!


3

In [16]:
# let's now do some brute forcing and find out average and max needed guesses

def bruteforce():
    """Try all possible words and return average, max needed guesses and worst case word."""
    max = s = 0
    worst_word = None
    for i in range(len(words)):
        if i % 100 == 0:
            print(f"word #{i}")
        guesses = play(i, False)
        s += guesses
        if guesses > max:
            max = guesses
            worst_word = i
    return s / len(words), max, worst_word

%time avg, max, worst_word = bruteforce()
print(f"Avg. guesses: {avg:.4f}; max attempts: {max} ({words[worst_word]})")

word #0
word #100
word #200
word #300
word #400
word #500
word #600
word #700
word #800
word #900
word #1000
word #1100
word #1200
word #1300
word #1400
word #1500
word #1600
word #1700
word #1800
word #1900
word #2000
word #2100
word #2200
word #2300
CPU times: user 1min 58s, sys: 26 ms, total: 1min 58s
Wall time: 1min 58s
Avg. guesses: 3.6350; max attempts: 8 (boxer)


In [17]:
# what happens with the worst word in the dataset

play(worst_word)

Guess: RAISE (score 60.00)
Y---Y
Remaining possible words: 102 (TREND ETHER DEMUR GRUEL POWER ...)
Guess: OUTER (score 7.69)
Y--GG
Remaining possible words: 16 (POWER GONER POKER HOVER JOKER ...)
Guess: MOWER (score 4.88)
-G-GG
Remaining possible words: 9 (GONER POKER HOVER JOKER CORER ...)
Guess: COVER (score 2.44)
-G-GG
Remaining possible words: 5 (GONER POKER JOKER FOYER BOXER)
Guess: POKER (score 1.20)
-G-GG
Remaining possible words: 3 (GONER FOYER BOXER)
Guess: GONER (score 0.67)
-G-GG
Remaining possible words: 2 (FOYER BOXER)
Guess: FOYER (score 0.00)
-G-GG
Remaining possible words: 1 (BOXER)
Guess: BOXER (score 0.00)
GGGGG
Correct!


8